version: '3.8'

services:
  primary-db:
    image: postgres:14
    container_name: primary-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: abs
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - ./primary-db-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    command: >
      postgres 
      -c wal_level=replica 
      -c max_wal_senders=10 
      -c max_replication_slots=10 
      -c hot_standby=on

  replica-db:
    image: postgres:14
    container_name: replica-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "6000:5432"
    depends_on:
      - primary-db
    volumes:
      - ./replica-db-data:/var/lib/postgresql/data